print(f"{'Anonymous 1: '}Choose a number.")
print(f"{'Anonymous 2: '}Ok, got it.")
print(f"{'Anonymous 1: '}Multiply it by itself and again by itself.")
print(f"{'Anonymous 2: '}Ok.")
print(f"{'Anonymous 1: '}What number did you get?")
print(f"{'Anonymous 2: '}{226}")
